### ISSUE TITLE
Compilation failure in mingw 12.2 due to missing ::at_quick_exit/::quick_exit/::timespec_get

### ISSUE THREAD

**Issue by Herringway** [charasyn/libsfcppu#1]
More specifically, these three errors:
`error: 'at_quick_exit' has not been declared in '::'`
`error: 'quick_exit' has not been declared in '::'`
`error: 'timespec_get' has not been declared in '::'`

See log here: https://github.com/Herringway/earthbound/actions/runs/6285659453/job/17068271313

**Comment by charasyn** [comment]
I was able to reproduce and fix on my side with https://github.com/charasyn/libsfcppu/commit/79a6cdce4dc440089db869f8fcded05040a5d521

**Comment by charasyn** [comment]
Confirmed working with https://github.com/charasyn/earthbound/actions/runs/6295292983
